/**
 * ALMAI CEO Dashboard - Master Data Store
 * Harmonized with ALMAI Platform Design Tokens (#33e818)
 * Designed for Calendar-First Executive Experience
 */

const CEO_DATA = {
  profile: {
    name: "Dr. Hendra Pratama",
    title: "Chief Executive Officer",
    company: "ALMAI Group Nusantara",
    avatar: "HP",
    email: "ceo@almai.id",
    status: "Active • Executive Mode",
    timezone: "Asia/Jakarta (WIB)",
    unreadNotifications: 3
  },

  companyInfo: {
    name: "PT. Alma Indonesia Raya",
    brand: "ALMAI",
    address: "Jl. Badak Agung No. 22 Kav. 3, Renon, Denpasar - Bali. 80226",
    phone: "0361-3610019",
    email: "finance@almai.id",
    npwp: "03.245.981.2-901.000",
    bankAccount: {
      bank: "Bank Central Asia (BCA)",
      accountNo: "882-019-3388",
      accountName: "PT ALMA INDONESIA RAYA"
    }
  },

  // Calendar Events (Meetings, Webinars, Deadlines, Events)
  calendarEvents: [
    {
      id: "evt-1",
      date: "2026-08-22",
      time: "14:00 - 15:30",
      title: "Rapat Pleno Direksi Q3 & Roadmap ALMAI 2026",
      category: "meeting",
      categoryName: "Rapat Direksi",
      location: "Boardroom HQ Lt. 8 & Google Meet Hybrid",
      meetUrl: "https://meet.google.com/alm-ceo-board",
      attendees: 5,
      priority: "high",
      description: "Evaluasi capaian Q2, alokasi budget Q3, dan penentuan target 25.000 pengguna aktif.",
      status: "upcoming"
    },
    {
      id: "evt-2",
      date: "2026-08-22",
      time: "16:30 - 17:30",
      title: "Penandatanganan MOU Kemitraan Sekuritas",
      category: "deadline",
      categoryName: "Deadline & MOU",
      location: "Menara Mandiri I Lt. 24, Jakarta",
      meetUrl: "",
      attendees: 3,
      priority: "high",
      description: "Penandatanganan nota kesepahaman integrasi data API dan bundling lisensi CWPA.",
      status: "upcoming"
    },
    {
      id: "evt-3",
      date: "2026-08-23",
      time: "10:00 - 11:30",
      title: "Review Bulanan Tim Produk & Algoritma AI",
      category: "meeting",
      categoryName: "Rapat Internal",
      location: "Zoom Online Meeting",
      meetUrl: "https://zoom.us/j/9910283411",
      attendees: 8,
      priority: "medium",
      description: "Sinkronisasi integrasi Trade Engine v4 dan Gemini AI assistant untuk pengguna pro.",
      status: "upcoming"
    },
    {
      id: "evt-4",
      date: "2026-08-24",
      time: "19:30 - 21:30",
      title: "Webinar: AI Wealth Architecture Masterclass 2026",
      category: "webinar",
      categoryName: "Webinar Akbar",
      location: "Zoom & YouTube Live (Private)",
      meetUrl: "https://zoom.us/j/98123450912",
      attendees: 850,
      priority: "high",
      description: "Webinar edukasi untuk 1,000+ peserta member ALMAI & calon kandidat WPA.",
      status: "upcoming"
    },
    {
      id: "evt-5",
      date: "2026-08-25",
      time: "23:59",
      title: "Jatuh Tempo: AWS Cloud Infrastructure & Biznet Dedicated",
      category: "bill",
      categoryName: "Jatuh Tempo Tagihan",
      location: "Finance Dashboard",
      meetUrl: "",
      attendees: 1,
      priority: "critical",
      description: "Pelunasan tagihan server utama AWS (EC2/RDS) dan bandwidth Biznet 500 Mbps.",
      status: "pending"
    },
    {
      id: "evt-6",
      date: "2026-08-27",
      time: "13:30 - 15:00",
      title: "Townhall Meeting All-Hands ALMAI",
      category: "general",
      categoryName: "Company Event",
      location: "Main Hall HQ & Live Stream",
      meetUrl: "https://meet.google.com/alm-townhall",
      attendees: 42,
      priority: "medium",
      description: "Pemberian apresiasi Top WPA Mentor dan pengumuman insentif kuartalan.",
      status: "upcoming"
    },
    {
      id: "evt-7",
      date: "2026-08-28",
      time: "15:00 - 16:00",
      title: "Interview Final VP of Engineering",
      category: "meeting",
      categoryName: "Executive Hiring",
      location: "CEO Office HQ",
      meetUrl: "",
      attendees: 2,
      priority: "medium",
      description: "Wawancara tahap akhir calon VP of Engineering dari fintech unicorn.",
      status: "upcoming"
    },
    {
      id: "evt-8",
      date: "2026-08-30",
      time: "19:00 - 21:00",
      title: "CWPA Mentorship: Strategi Sertifikasi & Portfolio Review",
      category: "webinar",
      categoryName: "Webinar Khusus",
      location: "Zoom Interactive Room",
      meetUrl: "https://zoom.us/j/77239019234",
      attendees: 120,
      priority: "high",
      description: "Bimbingan intensif persiapan sertifikasi profesi WPA dan bedah portofolio riil.",
      status: "upcoming"
    },
    {
      id: "evt-9",
      date: "2026-08-21",
      time: "09:00 - 10:30",
      title: "Audit Kepatuhan Bappebti Semester 1",
      category: "meeting",
      categoryName: "Compliance",
      location: "Ruang Rapat 2 HQ",
      meetUrl: "",
      attendees: 4,
      priority: "high",
      description: "Verifikasi kelengkapan berkas audit dan sertifikasi penasihat berjangka.",
      status: "done"
    },
    {
      id: "evt-10",
      date: "2026-08-20",
      time: "14:00 - 15:00",
      title: "Kickoff Integrasi Payment Gateway Xendit v2",
      category: "general",
      categoryName: "Tech Sprint",
      location: "Tech Lab",
      meetUrl: "",
      attendees: 6,
      priority: "medium",
      description: "Pengujian settlement instan QRIS dan Virtual Account.",
      status: "done"
    }
  ],

  // Executive Approvals (C-Level Decisions)
  approvals: [
    {
      id: "appr-1",
      date: "2026-08-22",
      time: "09:15 WIB",
      title: "Persetujuan Penambahan Server Cluster AI Trade Engine",
      requester: "Rian S. (CTO)",
      department: "Technology & AI",
      category: "Infrastruktur Cloud",
      amount: "Rp 45.000.000 / bln",
      rawAmount: 45000000,
      urgency: "High",
      icon: "fa-microchip",
      iconColor: "#33e818",
      status: "pending", // 'pending' | 'approved' | 'rejected'
      approvedAt: null,
      notes: "Kapasitas saat ini mencapai 82% karena lonjakan pendaftar baru. Diperlukan 4 instance node C5.4xlarge tambahan sebelum webinar akbar.",
      attachment: "Proposal_Cluster_AWS_Aug2026.pdf"
    },
    {
      id: "appr-2",
      date: "2026-08-22",
      time: "11:30 WIB",
      title: "Pencairan Komisi Mentor WPA & Referral Batch 3",
      requester: "Anita W. (CFO)",
      department: "Finance & Treasury",
      category: "Disbursement",
      amount: "Rp 68.500.000",
      rawAmount: 68500000,
      urgency: "High",
      icon: "fa-money-bill-transfer",
      iconColor: "#33e818",
      status: "pending",
      approvedAt: null,
      notes: "Total 48 mentor WPA dan affiliate terverifikasi sistem. Rekonsiliasi audit internal telah selesai 100%.",
      attachment: "Rekap_Komisi_Mentor_Batch3.xlsx"
    },
    {
      id: "appr-3",
      date: "2026-08-21",
      time: "17:00 WIB",
      title: "Penawaran Diskon Khusus Klien Korporasi (Bank Mandiri Sekuritas)",
      requester: "Dimas K. (Head of Business Dev)",
      department: "Partnership & Sales",
      category: "Commercial Terms",
      amount: "Nilai Kontrak: Rp 250.000.000",
      rawAmount: 250000000,
      urgency: "Medium",
      icon: "fa-handshake",
      iconColor: "#8b5cf6",
      status: "approved",
      approvedAt: "21 Agu 2026, 18:30 WIB",
      notes: "Permintaan potongan harga 12% untuk bundling 100 lisensi CWPA Korporat dengan komitmen kontrak 2 tahun.",
      attachment: "Draft_MOU_Mandiri_Sekuritas.pdf"
    },
    {
      id: "appr-4",
      date: "2026-08-21",
      time: "14:20 WIB",
      title: "Pengangkatan Staff Kunci: Lead Quant Researcher",
      requester: "Sarah L. (HR Director)",
      department: "Human Resources",
      category: "Talent Acquisition",
      amount: "Kompensasi: Rp 25.000.000 / bln",
      rawAmount: 25000000,
      urgency: "Normal",
      icon: "fa-user-plus",
      iconColor: "#06b6d4",
      status: "approved",
      approvedAt: "21 Agu 2026, 15:45 WIB",
      notes: "Kandidat memiliki pengalaman 7 tahun di hedge fund Singapura. Lolos background check dan live coding challenge.",
      attachment: "CV_Offering_Letter_LeadQuant.pdf"
    },
    {
      id: "appr-5",
      date: "2026-08-20",
      time: "10:15 WIB",
      title: "Pengadaan Lisensi Security Multi-Factor Auth Cloudflare Enterprise",
      requester: "Rian S. (CTO)",
      department: "Technology",
      category: "Cybersecurity",
      amount: "Rp 15.000.000",
      rawAmount: 15000000,
      urgency: "High",
      icon: "fa-shield-halved",
      iconColor: "#3b82f6",
      status: "approved",
      approvedAt: "20 Agu 2026, 11:00 WIB",
      notes: "Proteksi bot scalper dan perlindungan DDoS untuk server order execution.",
      attachment: "Cloudflare_Enterprise_SOW.pdf"
    },
    {
      id: "appr-6",
      date: "2026-08-25",
      time: "08:30 WIB",
      title: "Otorisasi Pembayaran Tagihan AWS & Biznet",
      requester: "Anita W. (CFO)",
      department: "Finance",
      category: "Invoice Payment",
      amount: "Rp 23.050.000",
      rawAmount: 23050000,
      urgency: "High",
      icon: "fa-file-invoice-dollar",
      iconColor: "#f59e0b",
      status: "pending",
      approvedAt: null,
      notes: "Pembayaran rutin bulanan sebelum jatuh tempo 25 Agustus 2026.",
      attachment: "Invoice_AWS_Biznet_Aug.pdf"
    }
  ],

  // Executive Notifications
  notifications: [
    {
      id: "notif-1",
      date: "2026-08-22",
      title: "Proposal Cluster Server Menunggu Persetujuan Anda",
      time: "1 jam yang lalu",
      category: "approval",
      categoryName: "Persetujuan",
      icon: "fa-signature",
      color: "#33e818",
      unread: true,
      status: "pending",
      relatedId: "appr-1"
    },
    {
      id: "notif-2",
      date: "2026-08-22",
      title: "Tagihan AWS & Biznet Mendekati Jatuh Tempo (3 Hari)",
      time: "25 menit yang lalu",
      category: "billing",
      categoryName: "Tagihan",
      icon: "fa-file-invoice-dollar",
      color: "#f59e0b",
      unread: true,
      status: "pending",
      relatedId: "bill-1"
    },
    {
      id: "notif-3",
      date: "2026-08-22",
      title: "Pendaftaran Webinar AI Mencapai 85% (850 Peserta)",
      time: "3 jam yang lalu",
      category: "webinar",
      categoryName: "Webinar",
      icon: "fa-chart-line",
      color: "#33e818",
      unread: true,
      status: "pending",
      relatedId: "evt-4"
    },
    {
      id: "notif-4",
      date: "2026-08-21",
      title: "Pencairan Komisi Mentor WPA Batch 2 Berhasil Ditransfer",
      time: "Kemarin, 16:30 WIB",
      category: "finance",
      categoryName: "Keuangan",
      icon: "fa-circle-check",
      color: "#33e818",
      unread: false,
      status: "done",
      relatedId: "appr-2"
    },
    {
      id: "notif-5",
      date: "2026-08-21",
      title: "Diskon Kemitraan Mandiri Sekuritas Telah Disetujui",
      time: "Kemarin, 18:35 WIB",
      category: "partnership",
      categoryName: "Kemitraan",
      icon: "fa-check-double",
      color: "#33e818",
      unread: false,
      status: "done",
      relatedId: "appr-3"
    },
    {
      id: "notif-6",
      date: "2026-08-20",
      title: "Pengadaan Security Cloudflare Enterprise Diotorisasi",
      time: "20 Agu 2026, 11:05 WIB",
      category: "tech",
      categoryName: "Teknologi",
      icon: "fa-shield-halved",
      color: "#33e818",
      unread: false,
      status: "done",
      relatedId: "appr-5"
    }
  ],

  // Bills & Invoices
  bills: [
    {
      id: "bill-1",
      date: "2026-08-25",
      serviceName: "AWS Cloud Infrastructure (EC2, RDS, S3)",
      vendor: "Amazon Web Services Inc.",
      category: "Server & Cloud",
      icon: "fa-server",
      iconColor: "#f59e0b",
      amount: "Rp 16.850.000",
      rawAmount: 16850000,
      dueDate: "25 Agu 2026",
      daysLeft: 3,
      status: "pending",
      invoiceNo: "INV-AWS-2026-08-882",
      paymentMethod: "Corporate Credit Card / Wire"
    },
    {
      id: "bill-2",
      date: "2026-08-25",
      serviceName: "Biznet Dedicated Internet 500 Mbps HQ",
      vendor: "PT Supra Primatama Nusantara",
      category: "Internet & Network",
      icon: "fa-wifi",
      iconColor: "#3b82f6",
      amount: "Rp 6.200.000",
      rawAmount: 6200000,
      dueDate: "25 Agu 2026",
      daysLeft: 3,
      status: "pending",
      invoiceNo: "INV-BIZ-74892",
      paymentMethod: "BCA Virtual Account"
    },
    {
      id: "bill-3",
      date: "2026-08-26",
      serviceName: "PLN Korporat HQ & Ruang Server",
      vendor: "PT PLN (Persero) Distribusi Jakarta",
      category: "Electricity & Utility",
      icon: "fa-bolt",
      iconColor: "#33e818",
      amount: "Rp 5.400.000",
      rawAmount: 5400000,
      dueDate: "26 Agu 2026",
      daysLeft: 4,
      status: "pending",
      invoiceNo: "PLN-ID-5401928",
      paymentMethod: "Auto Debit Mandiri"
    },
    {
      id: "bill-4",
      date: "2026-08-30",
      serviceName: "Cloudflare Enterprise & DDoS Protection",
      vendor: "Cloudflare Inc.",
      category: "Security & CDN",
      icon: "fa-shield-halved",
      iconColor: "#8b5cf6",
      amount: "Rp 3.750.000",
      rawAmount: 3750000,
      dueDate: "30 Agu 2026",
      daysLeft: 8,
      status: "pending",
      invoiceNo: "CF-INV-99231",
      paymentMethod: "Corporate Card"
    }
  ],

  // Official Invoices for modal viewing
  invoices: [
    {
      invoiceNumber: "INV-AWS-2026-08-882",
      type: "payable",
      typeText: "Tagihan Masuk (Vendor)",
      title: "AWS Cloud Infrastructure - August 2026",
      issuer: "Amazon Web Services Inc.",
      issuerAddress: "410 Terry Ave N, Seattle, WA 98109, United States",
      recipient: "PT. Alma Indonesia Raya",
      recipientAddress: "Jl. Badak Agung No. 22 Kav. 3, Renon, Denpasar - Bali. 80226",
      issueDate: "15 Agu 2026",
      dueDate: "25 Agu 2026",
      status: "pending",
      statusText: "MENUNGGU PEMBAYARAN",
      statusColor: "#f59e0b",
      subtotal: 15180180,
      tax: 1669820,
      total: 16850000,
      formattedTotal: "Rp 16.850.000",
      paymentChannel: "Corporate Wire Transfer / Xendit Corporate Card",
      accountInfo: "BCA Corporate: 882-019-3388 a.n PT ALMA INDONESIA RAYA",
      items: [
        { desc: "Amazon EC2 Compute Instances (Cluster C5.4xlarge Trade Engine)", qty: 4, unitPrice: 2450000, total: 9800000 },
        { desc: "Amazon RDS Multi-AZ PostgreSQL & MySQL High Availability", qty: 2, unitPrice: 1940090, total: 3880180 },
        { desc: "Amazon S3 Object Storage & CloudFront Global CDN", qty: 1, unitPrice: 1500000, total: 1500000 }
      ],
      notes: "Pembayaran wajib diselesaikan sebelum jatuh tempo 25 Agustus 2026 untuk menjamin kelancaran sistem 99.98% SLA."
    },
    {
      invoiceNumber: "INV-BIZ-74892",
      type: "payable",
      typeText: "Tagihan Masuk (Vendor)",
      title: "Biznet Dedicated Internet 500 Mbps HQ",
      issuer: "PT Supra Primatama Nusantara (Biznet)",
      issuerAddress: "MidPlaza 2, 8th Floor, Jl. Jend. Sudirman Kav 10-11, Jakarta 10220",
      recipient: "PT. Alma Indonesia Raya",
      recipientAddress: "Jl. Badak Agung No. 22 Kav. 3, Renon, Denpasar - Bali. 80226",
      issueDate: "10 Agu 2026",
      dueDate: "25 Agu 2026",
      status: "pending",
      statusText: "MENUNGGU PEMBAYARAN",
      statusColor: "#f59e0b",
      subtotal: 5585585,
      tax: 614415,
      total: 6200000,
      formattedTotal: "Rp 6.200.000",
      paymentChannel: "BCA Virtual Account",
      accountInfo: "VA BCA: 70012-9840-1928",
      items: [
        { desc: "Biznet Dedicated Metronet 500 Mbps 1:1 CIR - HQ Renon", qty: 1, unitPrice: 5000000, total: 5000000 },
        { desc: "Static IP Public Block /29 Subnet", qty: 1, unitPrice: 585585, total: 585585 }
      ],
      notes: "Tagihan rutin bulanan internet dedicated kantor pusat dan trading desk."
    },
    {
      invoiceNumber: "INV-ALM-2026-08-101",
      type: "receivable",
      typeText: "Faktur Kemitraan (Pendapatan)",
      title: "Lisensi CWPA Enterprise 100 User - Bank Mandiri Sekuritas",
      issuer: "PT. Alma Indonesia Raya (ALMAI)",
      issuerAddress: "Jl. Badak Agung No. 22 Kav. 3, Renon, Denpasar - Bali. 80226",
      recipient: "PT Mandiri Sekuritas",
      recipientAddress: "Menara Mandiri I Lt. 24, Jl. Jend. Sudirman Kav. 54-55, Jakarta 12190",
      issueDate: "18 Agu 2026",
      dueDate: "31 Agu 2026",
      status: "pending",
      statusText: "MENUNGGU PEMBAYARAN MITRA",
      statusColor: "#3b82f6",
      subtotal: 225225225,
      tax: 24774775,
      total: 250000000,
      formattedTotal: "Rp 250.000.000",
      paymentChannel: "Mandiri Corporate Escrow Transfer",
      accountInfo: "Mandiri Giro: 137-00-1928394-2 a.n PT ALMA INDONESIA RAYA",
      items: [
        { desc: "CWPA Enterprise Professional Certification Seats (100 Peserta)", qty: 100, unitPrice: 2000000, total: 200000000 },
        { desc: "Dedicated Mentor WPA Assigned Coach & Exam Simulation Portal", qty: 1, unitPrice: 25225225, total: 25225225 }
      ],
      notes: "Kontrak kemitraan korporasi tahunan. Term of Payment: Net 14 Days."
    }
  ]
};
