<?= $this->extend($layout) ?>
<?= $this->section('content') ?>
<div class="space-y-5" id="crmApp" data-api="<?= esc($apiBase) ?>">
    <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div><p class="text-xs font-bold uppercase tracking-[.22em] text-accent">Customer Relationship Management</p><h1 class="mt-1 text-2xl font-extrabold sm:text-3xl">Monitoring Chat & Auto Reply</h1><p class="mt-1 text-sm text-gray-400">Pantau percakapan Balesotomatis, PIC, follow-up, dan SLA dalam satu layar.</p></div>
        <div class="flex rounded-xl border border-white/10 bg-white/[.03] p-1 text-xs font-semibold">
            <button class="crm-tab rounded-lg bg-accent px-4 py-2 text-black" data-tab="monitoring">Monitoring</button>
            <button class="crm-tab rounded-lg px-4 py-2 text-gray-400" data-tab="recap">Rekap</button>
            <button class="crm-tab rounded-lg px-4 py-2 text-gray-400" data-tab="automation">Automation</button>
        </div>
    </div>

    <div id="flash" class="hidden rounded-xl border px-4 py-3 text-sm"></div>
    <section id="tab-monitoring" class="crm-panel space-y-5">
        <div id="summaryCards" class="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7"></div>
        <div class="dash-card p-4">
            <form id="filters" class="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
                <input name="search" class="rounded-xl border border-white/10 bg-black px-4 py-3 text-sm outline-none focus:border-accent" placeholder="Cari nama, telepon, pesan...">
                <select name="status" class="rounded-xl border border-white/10 bg-black px-4 py-3 text-sm"><option value="">Semua status</option><?php foreach(['NEW','AUTO_REPLIED','UNREAD','IN_PROGRESS','FOLLOW_UP','DONE'] as $s): ?><option><?= $s ?></option><?php endforeach ?></select>
                <select name="pic" class="rounded-xl border border-white/10 bg-black px-4 py-3 text-sm"><option value="">Semua PIC</option><?php foreach($pics as $pic): ?><option value="<?= $pic['id'] ?>"><?= esc($pic['name']) ?></option><?php endforeach ?></select>
                <input type="date" name="date" class="rounded-xl border border-white/10 bg-black px-4 py-3 text-sm">
                <button class="rounded-xl bg-accent px-4 py-3 font-bold text-black"><i class="fas fa-filter mr-2"></i>Terapkan</button>
            </form>
        </div>
        <div class="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(380px,.75fr)]">
            <div class="dash-card overflow-hidden">
                <div class="border-b border-white/10 px-5 py-4"><h2 class="font-bold">Antrean Percakapan</h2><p id="resultMeta" class="text-xs text-gray-500">Memuat data...</p></div>
                <div class="overflow-x-auto"><table class="w-full min-w-[780px] text-left text-sm"><thead class="bg-white/[.03] text-xs uppercase text-gray-500"><tr><th class="p-4">User</th><th class="p-4">Pesan terakhir</th><th class="p-4">Status</th><th class="p-4">PIC</th><th class="p-4">SLA</th></tr></thead><tbody id="sessionRows" class="divide-y divide-white/[.06]"></tbody></table></div>
            </div>
            <aside id="detailPanel" class="dash-card min-h-[600px] p-5"><div class="flex h-full min-h-[520px] items-center justify-center text-center text-gray-500"><div><i class="fas fa-comments mb-3 text-4xl"></i><p>Pilih percakapan untuk melihat detail.</p></div></div></aside>
        </div>
    </section>

    <section id="tab-recap" class="crm-panel hidden space-y-5">
        <div class="grid gap-5 xl:grid-cols-2"><div class="dash-card p-5"><h2 class="mb-4 font-bold">Percakapan 14 Hari</h2><canvas id="dailyChart" height="150"></canvas></div><div class="dash-card p-5"><h2 class="mb-4 font-bold">Kinerja per PIC</h2><canvas id="picChart" height="150"></canvas></div></div>
    </section>

    <section id="tab-automation" class="crm-panel hidden grid gap-5 lg:grid-cols-[420px_1fr]">
        <form id="workflowForm" class="dash-card space-y-4 p-5"><div><h2 class="font-bold">Workflow Baru</h2><p class="text-xs text-gray-500">Trigger → conditions/actions dalam JSON.</p></div><input name="name" required class="w-full rounded-xl border border-white/10 bg-black px-4 py-3 text-sm" placeholder="Nama workflow"><select name="trigger" class="w-full rounded-xl border border-white/10 bg-black px-4 py-3 text-sm"><option value="user_registered">User terdaftar</option><option value="message_received">Pesan masuk</option><option value="status_changed">Status berubah</option></select><textarea name="workflow_json" rows="10" class="w-full rounded-xl border border-white/10 bg-black p-4 font-mono text-xs text-green-300">[
  {"action":"SEND_MESSAGE","message":"Halo, ada yang bisa kami bantu?"},
  {"action":"CHANGE_STATUS","status":"FOLLOW_UP"}
]</textarea><button class="w-full rounded-xl bg-accent px-4 py-3 font-bold text-black">Simpan Workflow</button></form>
        <div class="dash-card p-5"><h2 class="mb-4 font-bold">Workflow Aktif</h2><div class="space-y-3" id="workflowList"><?php if(!$workflows): ?><p class="text-sm text-gray-500">Belum ada workflow.</p><?php endif ?><?php foreach($workflows as $flow): ?><div class="flex items-center justify-between rounded-xl border border-white/10 p-4"><div><p class="font-semibold"><?= esc($flow['name']) ?></p><p class="text-xs text-gray-500"><?= esc($flow['trigger']) ?></p></div><button onclick="toggleWorkflow(<?= $flow['id'] ?>,<?= $flow['is_active']?'0':'1' ?>)" class="rounded-lg px-3 py-2 text-xs font-bold <?= $flow['is_active']?'bg-accent/15 text-accent':'bg-white/10 text-gray-400' ?>"><?= $flow['is_active']?'AKTIF':'NONAKTIF' ?></button></div><?php endforeach ?></div></div>
    </section>
</div>
<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<script>
const app=document.getElementById('crmApp'),api=app.dataset.api,csrfName='<?= csrf_token() ?>',csrfHash='<?= csrf_hash() ?>';let selectedId=null,dailyChart=null,picChart=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const labels={NEW:'Baru',AUTO_REPLIED:'Auto Reply',UNREAD:'Belum Dibaca',IN_PROGRESS:'Diproses',FOLLOW_UP:'Follow Up',DONE:'Selesai'};
const colors={NEW:'text-blue-300 bg-blue-500/10',AUTO_REPLIED:'text-violet-300 bg-violet-500/10',UNREAD:'text-red-300 bg-red-500/10',IN_PROGRESS:'text-amber-300 bg-amber-500/10',FOLLOW_UP:'text-cyan-300 bg-cyan-500/10',DONE:'text-green-300 bg-green-500/10'};
async function get(url){const r=await fetch(url,{headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error(j.message||'Permintaan gagal');return j}
async function post(url,data){data.append(csrfName,csrfHash);const r=await fetch(url,{method:'POST',body:data,headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error(j.message||'Permintaan gagal');return j}
function flash(message,bad=false){const e=document.getElementById('flash');e.className=`rounded-xl border px-4 py-3 text-sm ${bad?'border-red-500/30 bg-red-500/10 text-red-300':'border-accent/30 bg-accent/10 text-accent'}`;e.textContent=message;setTimeout(()=>e.classList.add('hidden'),4500)}
async function loadSummary(){const j=await get(api+'/dashboard/summary'),d=j.data;document.getElementById('summaryCards').innerHTML=[...Object.keys(labels),'TOTAL_TODAY'].map(k=>`<div class="dash-card p-4"><p class="text-2xl font-extrabold">${d[k]||0}</p><p class="mt-1 text-[11px] text-gray-500">${k==='TOTAL_TODAY'?'User Baru Hari Ini':labels[k]}</p></div>`).join('')}
function sla(row){if(row.status==='DONE')return '<span class="text-green-400">Selesai</span>';const now=Date.now(),start=new Date((row.sla_started_at||row.created_at).replace(' ','T')),secs=Math.max(0,Math.floor((now-start)/1000)),h=String(Math.floor(secs/3600)).padStart(2,'0'),m=String(Math.floor(secs%3600/60)).padStart(2,'0'),s=String(secs%60).padStart(2,'0'),lateFollow=row.status==='FOLLOW_UP'&&row.follow_up_due_at&&new Date(row.follow_up_due_at.replace(' ','T'))<now;return `<span class="${secs>=900?'text-red-400':lateFollow||secs>=300?'text-amber-400':'text-green-400'}">${h}:${m}:${s}</span>`}
async function loadSessions(){const qs=new URLSearchParams(new FormData(document.getElementById('filters'))),j=await get(api+'/sessions?'+qs);document.getElementById('resultMeta').textContent=`${j.pagination.total} percakapan`;document.getElementById('sessionRows').innerHTML=j.data.length?j.data.map(r=>`<tr onclick="openSession(${r.id})" class="cursor-pointer hover:bg-white/[.035] ${selectedId==r.id?'bg-accent/[.05]':''}"><td class="p-4"><p class="font-semibold">${esc(r.customer_name)}</p><p class="text-xs text-gray-500">${esc(r.phone||r.platform_user_id)}</p></td><td class="max-w-[260px] p-4"><p class="truncate">${esc(r.last_message)}</p><p class="text-xs text-gray-500">${esc(r.last_message_at||'-')}</p></td><td class="p-4"><span class="rounded-lg px-2 py-1 text-[10px] font-bold ${colors[r.status]||''}">${esc(labels[r.status]||r.status)}</span></td><td class="p-4">${esc(r.assigned_name||'Belum ada')}</td><td class="p-4 text-xs">${sla(r)}</td></tr>`).join(''):'<tr><td colspan="5" class="p-12 text-center text-gray-500">Tidak ada percakapan.</td></tr>'}
async function openSession(id){selectedId=id;await loadSessions();const j=await get(api+'/sessions/'+id),s=j.data,msgs=s.messages.filter(m=>!+m.is_internal_note),notes=s.messages.filter(m=>+m.is_internal_note);document.getElementById('detailPanel').innerHTML=`<div class="space-y-4"><div><p class="text-xs text-gray-500">#CRM-${String(s.id).padStart(5,'0')}</p><h2 class="text-xl font-bold">${esc(s.customer_name)}</h2><p class="text-xs text-gray-500">${esc(s.phone||s.platform_user_id)} · ${esc(s.email||'')}</p></div><div class="grid grid-cols-2 gap-2"><select id="statusSelect" class="rounded-xl border border-white/10 bg-black p-3 text-xs">${Object.keys(labels).map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('')}</select><select id="picSelect" class="rounded-xl border border-white/10 bg-black p-3 text-xs"><option value="">Pilih PIC</option><?php foreach($pics as $pic): ?><option value="<?= $pic['id'] ?>" ${s.assigned_to==<?= $pic['id'] ?>?'selected':''}><?= esc($pic['name']) ?></option><?php endforeach ?></select></div><div class="h-[300px] space-y-2 overflow-y-auto rounded-xl border border-white/10 bg-black/50 p-3">${msgs.map(m=>`<div class="${m.sender_type==='user'?'mr-10 bg-white/[.07]':'ml-10 bg-accent/10'} rounded-xl p-3"><p class="text-[10px] font-bold uppercase text-gray-500">${esc(m.sender_type)} ${+m.is_auto_reply?'· AUTO':''}</p><p class="mt-1 whitespace-pre-wrap text-sm">${esc(m.message_body)}</p><p class="mt-1 text-right text-[9px] text-gray-600">${esc(m.created_at)}</p></div>`).join('')||'<p class="text-center text-xs text-gray-500">Belum ada pesan.</p>'}</div><form id="sendForm" class="space-y-2"><textarea name="message" rows="3" required class="w-full rounded-xl border border-white/10 bg-black p-3 text-sm" placeholder="Tulis balasan melalui Balesotomatis..."></textarea><label class="flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" name="internal_note" value="1"> Catatan internal (tidak dikirim ke user)</label><button class="w-full rounded-xl bg-accent p-3 font-bold text-black"><i class="fas fa-paper-plane mr-2"></i>Kirim</button></form><details class="rounded-xl border border-white/10 p-3"><summary class="cursor-pointer text-xs font-semibold">Timeline & catatan (${s.timeline.length+notes.length})</summary><div class="mt-3 space-y-2 text-xs">${s.timeline.map(t=>`<p><span class="text-gray-500">${esc(t.created_at)}</span> ${esc(t.from_status||'START')} → <b>${esc(t.to_status)}</b> ${esc(t.note||'')}</p>`).join('')}${notes.map(n=>`<p class="text-amber-300"><i class="fas fa-note-sticky"></i> ${esc(n.message_body)}</p>`).join('')}</div></details></div>`;
document.getElementById('statusSelect').onchange=async e=>{const f=new FormData;f.append('status',e.target.value);try{await post(api+`/sessions/${id}/status`,f);flash('Status diperbarui');await Promise.all([loadSummary(),openSession(id)])}catch(x){flash(x.message,true)}};
document.getElementById('picSelect').onchange=async e=>{if(!e.target.value)return;const f=new FormData;f.append('pic_id',e.target.value);try{await post(api+`/sessions/${id}/assign`,f);flash('PIC diperbarui');await openSession(id)}catch(x){flash(x.message,true)}};
document.getElementById('sendForm').onsubmit=async e=>{e.preventDefault();try{await post(api+`/sessions/${id}/messages`,new FormData(e.target));flash('Pesan berhasil diproses');await Promise.all([loadSummary(),openSession(id)])}catch(x){flash(x.message,true)}}}
async function loadRecap(){const j=await get(api+'/recap'),d=j.data;dailyChart?.destroy();picChart?.destroy();dailyChart=new Chart(document.getElementById('dailyChart'),{type:'line',data:{labels:d.daily.map(x=>x.label),datasets:[{label:'Total',data:d.daily.map(x=>x.total),borderColor:'#33e818'},{label:'Selesai',data:d.daily.map(x=>x.done),borderColor:'#60a5fa'}]}});picChart=new Chart(document.getElementById('picChart'),{type:'bar',data:{labels:d.by_pic.map(x=>x.label),datasets:[{label:'Total',data:d.by_pic.map(x=>x.total),backgroundColor:'#33e818'}]}})}
document.getElementById('filters').onsubmit=e=>{e.preventDefault();loadSessions().catch(x=>flash(x.message,true))};document.getElementById('workflowForm').onsubmit=async e=>{e.preventDefault();try{await post(api+'/automations',new FormData(e.target));location.reload()}catch(x){flash(x.message,true)}};
async function toggleWorkflow(id,state){const f=new FormData;f.append('is_active',state);try{await post(api+'/automations/'+id,f);location.reload()}catch(x){flash(x.message,true)}}
document.querySelectorAll('.crm-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.crm-tab').forEach(x=>x.className='crm-tab rounded-lg px-4 py-2 text-gray-400');b.className='crm-tab rounded-lg bg-accent px-4 py-2 text-black';document.querySelectorAll('.crm-panel').forEach(x=>x.classList.add('hidden'));document.getElementById('tab-'+b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='recap')loadRecap().catch(x=>flash(x.message,true))});
Promise.all([loadSummary(),loadSessions()]).catch(x=>flash(x.message,true));setInterval(()=>{loadSummary();loadSessions()},15000);
</script>
<?= $this->endSection() ?>
