<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KelasSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'wpa_id' => 1,
                'title' => 'Gold Trading Masterclass',
                'slug' => 'gold-trading-masterclass',
                'thumbnail' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600',
                'price' => 18000000,
                'original_price' => 25000000,
                'duration' => '15 Jam',
                'modules' => 30,
                'level' => 'Advanced',
                'rating' => 4.9,
                'students' => 1234,
                'category' => 'Gold Trading',
                'mode' => 'Offline',
                'location' => 'Bali',
                'type' => 'recorded',
                'description' => 'Pelajari strategi trading gold yang telah terbukti menghasilkan profit konsisten dari WPA bersertifikat.',
                'highlights' => '["Money Management","Risk Management","Entry & Exit Strategy","Psychology Trading"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 2,
                'title' => 'Forex Fundamental Analysis',
                'slug' => 'forex-fundamental-analysis',
                'thumbnail' => 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=600',
                'price' => 12000000,
                'original_price' => 18000000,
                'duration' => '12 Jam',
                'modules' => 24,
                'level' => 'Intermediate',
                'rating' => 4.8,
                'students' => 856,
                'category' => 'Forex Trading',
                'mode' => 'Online',
                'location' => 'Zoom',
                'type' => 'live',
                'zoom_link' => 'https://zoom.us/j/123456789',
                'zoom_meeting_id' => '123 456 789',
                'zoom_password' => 'almai123',
                'schedule' => 'Setiap Sabtu, 09:00 - 12:00 WIB',
                'next_session' => '2025-12-28',
                'description' => 'Kuasai analisis fundamental untuk trading forex. Pahami dampak berita ekonomi terhadap pergerakan mata uang.',
                'highlights' => '["Economic Calendar","News Trading","Interest Rate Analysis","GDP & Inflation"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 7,
                'title' => 'Crypto Trading untuk Pemula',
                'slug' => 'crypto-trading-untuk-pemula',
                'thumbnail' => 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=600',
                'price' => 8000000,
                'original_price' => 12000000,
                'duration' => '10 Jam',
                'modules' => 20,
                'level' => 'Beginner',
                'rating' => 4.9,
                'students' => 2345,
                'category' => 'Crypto Trading',
                'mode' => 'Online',
                'location' => 'Zoom',
                'type' => 'recorded',
                'description' => 'Panduan lengkap memulai trading cryptocurrency. Dari dasar hingga strategi profit konsisten.',
                'highlights' => '["Blockchain Basics","Technical Analysis","DeFi Trading","Risk Management"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 4,
                'title' => 'Commodity Trading Mastery',
                'slug' => 'commodity-trading-mastery',
                'thumbnail' => 'https://images.unsplash.com/photo-1516937941344-00b4e0337589?w=600',
                'price' => 15000000,
                'original_price' => 22000000,
                'duration' => '14 Jam',
                'modules' => 28,
                'level' => 'Advanced',
                'rating' => 4.7,
                'students' => 567,
                'category' => 'Commodity Trading',
                'mode' => 'Offline',
                'location' => 'Jakarta',
                'type' => 'recorded',
                'description' => 'Strategi trading komoditas (CPO, Kopi, Kakao) di pasar berjangka Indonesia.',
                'highlights' => '["Supply & Demand","Seasonal Pattern","Hedging Strategy","Contract Specification"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 5,
                'title' => 'Index Trading Strategy',
                'slug' => 'index-trading-strategy',
                'thumbnail' => 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=600',
                'price' => 10000000,
                'original_price' => 15000000,
                'duration' => '12 Jam',
                'modules' => 24,
                'level' => 'Intermediate',
                'rating' => 4.9,
                'students' => 789,
                'category' => 'Index Trading',
                'mode' => 'Hybrid',
                'location' => 'Bali / Zoom',
                'type' => 'recorded',
                'description' => 'Strategi trading index (Hang Seng, Nikkei, Kospi) dengan win rate tinggi.',
                'highlights' => '["Market Structure","Session Trading","Correlation Analysis","Position Sizing"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 3,
                'title' => 'Build Your Own Expert Advisor',
                'slug' => 'build-your-own-expert-advisor',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600',
                'price' => 25000000,
                'original_price' => 35000000,
                'duration' => '20 Jam',
                'modules' => 40,
                'level' => 'Advanced',
                'rating' => 4.8,
                'students' => 345,
                'category' => 'Algorithmic Trading',
                'mode' => 'Online',
                'location' => 'Zoom',
                'type' => 'recorded',
                'description' => 'Belajar membuat robot trading (EA) sendiri dengan MQL4/MQL5.',
                'highlights' => '["MQL Programming","Backtesting","Optimization","Risk Parameters"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 9,
                'title' => 'Money Management Anti-MC',
                'slug' => 'money-management-anti-mc',
                'thumbnail' => 'https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=600',
                'price' => 7500000,
                'original_price' => 10000000,
                'duration' => '8 Jam',
                'modules' => 16,
                'level' => 'Beginner',
                'rating' => 4.8,
                'students' => 1567,
                'category' => 'Risk Management',
                'mode' => 'Online',
                'location' => 'Zoom',
                'type' => 'recorded',
                'description' => 'Teknik money management yang terbukti mencegah Margin Call.',
                'highlights' => '["Lot Calculation","Risk per Trade","Drawdown Control","Recovery Strategy"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'wpa_id' => 8,
                'title' => 'Technical Analysis Complete',
                'slug' => 'technical-analysis-complete',
                'thumbnail' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600',
                'price' => 9000000,
                'original_price' => 14000000,
                'duration' => '15 Jam',
                'modules' => 30,
                'level' => 'Intermediate',
                'rating' => 4.7,
                'students' => 2134,
                'category' => 'Technical Analysis',
                'mode' => 'Hybrid',
                'location' => 'Bali / Zoom',
                'type' => 'recorded',
                'description' => 'Panduan lengkap analisis teknikal dari dasar hingga advanced.',
                'highlights' => '["Chart Pattern","Candlestick","Indicator","Price Action"]',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        foreach ($data as $row) {
            $this->db->table('kelas')->insert($row);
        }
    }
}
