<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow">
    <title><?= esc($title ?? 'CEO Login - ALMAI') ?></title>
    <style>
        :root{--bg:#050706;--surface:#101410;--line:rgba(255,255,255,.09);--text:#f8faf8;--muted:#8d998f;--accent:#33e818;--danger:#fb7185}*{box-sizing:border-box}html,body{min-height:100%}body{margin:0;min-height:100vh;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--text);background:radial-gradient(circle at 16% 8%,rgba(51,232,24,.09),transparent 28rem),radial-gradient(circle at 86% 86%,rgba(51,232,24,.05),transparent 24rem),var(--bg);display:grid;place-items:center;padding:32px 20px;overflow-x:hidden}body::before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.35;background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:54px 54px;mask-image:linear-gradient(to bottom,black,transparent 88%)}
        .login-shell{position:relative;z-index:1;width:min(980px,100%)}.brand-top{display:inline-flex;align-items:center;gap:11px;margin:0 0 20px 4px;color:var(--text);text-decoration:none}.brand-top img{width:38px;height:38px;object-fit:contain}.brand-top strong{font-size:22px;letter-spacing:-.03em}.login-card{display:grid;grid-template-columns:.9fr 1.1fr;min-height:570px;overflow:hidden;border:1px solid var(--line);border-radius:26px;background:rgba(12,15,13,.92);box-shadow:0 34px 90px rgba(0,0,0,.48);backdrop-filter:blur(18px)}
        .brand-panel{position:relative;padding:52px 44px;background:linear-gradient(155deg,rgba(51,232,24,.16),transparent 56%),#090c09;border-right:1px solid var(--line);display:flex;flex-direction:column;justify-content:space-between}.brand-panel::after{content:"";position:absolute;width:220px;height:220px;border-radius:999px;right:-90px;bottom:-100px;background:rgba(51,232,24,.13);filter:blur(20px)}.eyebrow{display:inline-flex;align-items:center;gap:8px;width:fit-content;padding:7px 11px;border:1px solid rgba(51,232,24,.24);border-radius:999px;background:rgba(51,232,24,.07);color:#9cfb8d;font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.eyebrow-dot{width:7px;height:7px;border-radius:50%;background:var(--accent);box-shadow:0 0 12px var(--accent)}.brand-panel h1{margin:25px 0 15px;max-width:340px;font-size:clamp(34px,4.5vw,52px);line-height:1.03;letter-spacing:-.055em}.brand-panel p{max-width:340px;margin:0;color:var(--muted);line-height:1.7;font-size:14px}.secure-note{position:relative;z-index:1;display:flex;align-items:center;gap:10px;color:#b8c3ba;font-size:12px}.secure-note svg{width:18px;color:var(--accent)}
        .form-panel{padding:52px 54px;display:flex;flex-direction:column;justify-content:center}.form-icon{width:46px;height:46px;display:grid;place-items:center;border-radius:14px;color:#091006;background:var(--accent);box-shadow:0 0 28px rgba(51,232,24,.18)}.form-icon svg{width:22px}.form-panel h2{margin:20px 0 7px;font-size:28px;letter-spacing:-.035em}.form-panel>p{margin:0 0 29px;color:var(--muted);font-size:14px;line-height:1.55}.alert{margin-bottom:18px;padding:12px 14px;border-radius:12px;font-size:13px;line-height:1.5}.alert-success{color:#a7f3a0;border:1px solid rgba(51,232,24,.25);background:rgba(51,232,24,.08)}.alert-error{color:#fecdd3;border:1px solid rgba(251,113,133,.25);background:rgba(251,113,133,.08)}.alert ul{margin:0;padding-left:18px}
        .field{margin-bottom:18px}.field label{display:block;margin-bottom:8px;color:#cbd5cc;font-size:13px;font-weight:650}.input-wrap{position:relative}.input-wrap>svg{position:absolute;left:15px;top:50%;width:18px;transform:translateY(-50%);color:#667069;pointer-events:none}.input-wrap input{width:100%;height:52px;padding:0 47px;border:1px solid rgba(255,255,255,.13);border-radius:13px;outline:none;color:var(--text);background:#070907;font:inherit;font-size:14px;transition:border-color .18s,box-shadow .18s,background .18s}.input-wrap input::placeholder{color:#555e57}.input-wrap input:focus{border-color:rgba(51,232,24,.68);background:#090c09;box-shadow:0 0 0 4px rgba(51,232,24,.08)}.password-toggle{position:absolute;right:8px;top:50%;width:38px;height:38px;transform:translateY(-50%);display:grid;place-items:center;border:0;border-radius:9px;color:#7e8980;background:transparent;cursor:pointer}.password-toggle:hover,.password-toggle:focus-visible{color:var(--text);background:rgba(255,255,255,.06);outline:none}.password-toggle svg{width:19px}.form-options{display:flex;align-items:center;justify-content:space-between;margin:-2px 0 22px}.remember{display:inline-flex;align-items:center;gap:9px;color:var(--muted);font-size:13px;cursor:pointer}.remember input{width:16px;height:16px;margin:0;accent-color:var(--accent)}
        .submit-btn{width:100%;height:53px;display:inline-flex;align-items:center;justify-content:center;gap:9px;border:0;border-radius:13px;color:#071004;background:var(--accent);font:inherit;font-size:14px;font-weight:850;cursor:pointer;box-shadow:0 13px 28px rgba(51,232,24,.15);transition:transform .18s,background .18s,box-shadow .18s}.submit-btn:hover{background:#43f22a;transform:translateY(-1px);box-shadow:0 16px 32px rgba(51,232,24,.22)}.submit-btn:active{transform:translateY(0)}.submit-btn svg{width:18px}.footer-note{margin-top:22px;color:#566058;text-align:center;font-size:11px;line-height:1.5}@media(max-width:780px){body{padding:22px 14px;place-items:start center}.brand-top{margin-top:8px}.login-card{grid-template-columns:1fr;min-height:auto;border-radius:22px}.brand-panel{padding:30px 28px;border-right:0;border-bottom:1px solid var(--line)}.brand-panel h1{margin-top:18px;font-size:34px}.brand-panel p{line-height:1.55}.secure-note{margin-top:27px}.form-panel{padding:34px 28px 38px}}@media(max-width:430px){.brand-panel{display:none}.brand-top{margin-bottom:14px}.form-panel{padding:31px 22px 33px}.form-panel h2{font-size:25px}}
    </style>
</head>
<body>
<main class="login-shell">
    <a href="<?= base_url('/') ?>" class="brand-top" aria-label="Kembali ke halaman utama ALMAI"><img src="<?= base_url('images/alma.gif') ?>" alt="Logo ALMAI"><strong>ALMAI</strong></a>
    <section class="login-card" aria-labelledby="login-title">
        <aside class="brand-panel">
            <div><span class="eyebrow"><span class="eyebrow-dot"></span> Executive access</span><h1>Satu pintu untuk keputusan penting.</h1><p>Pantau kinerja, risiko, agenda, dan approval perusahaan melalui ruang kerja eksekutif ALMAI.</p></div>
            <div class="secure-note"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg><span>Akses terbatas untuk akun CEO terverifikasi.</span></div>
        </aside>
        <div class="form-panel">
            <div class="form-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="m2 4 3 12h14l3-12-6 5-4-7-4 7-6-5Z"/><path d="M5 20h14"/></svg></div>
            <h2 id="login-title">CEO Executive Login</h2><p>Masuk menggunakan akun CEO untuk membuka dashboard eksekutif.</p>
            <?php if (session()->getFlashdata('success')): ?><div class="alert alert-success" role="status"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
            <?php if (session()->getFlashdata('error')): ?><div class="alert alert-error" role="alert"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
            <?php if (session()->getFlashdata('errors')): ?><div class="alert alert-error" role="alert"><ul><?php foreach (session()->getFlashdata('errors') as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></div><?php endif; ?>
            <form action="<?= base_url('ceo/login') ?>" method="post">
                <?= csrf_field() ?>
                <div class="field"><label for="ceo-email">Email</label><div class="input-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-10 6L2 7"/></svg><input id="ceo-email" type="email" name="email" required autocomplete="username" inputmode="email" value="<?= esc(old('email'), 'attr') ?>" placeholder="nama@almai.id"></div></div>
                <div class="field"><label for="ceo-password">Password</label><div class="input-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg><input id="ceo-password" type="password" name="password" required autocomplete="current-password" placeholder="Masukkan password"><button class="password-toggle" type="button" aria-label="Tampilkan password" aria-pressed="false" onclick="togglePassword(this)"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M2.1 12a10 10 0 0 1 19.8 0 10 10 0 0 1-19.8 0Z"/><circle cx="12" cy="12" r="3"/></svg></button></div></div>
                <button type="submit" class="submit-btn"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" aria-hidden="true"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><path d="m10 17 5-5-5-5"/><path d="M15 12H3"/></svg>Masuk ke Dashboard</button>
            </form>
            <div class="footer-note">Aktivitas login dilindungi pembatasan percobaan dan sesi terenkripsi.</div>
        </div>
    </section>
</main>
<script>function togglePassword(button){const input=document.getElementById('ceo-password');const visible=input.type==='text';input.type=visible?'password':'text';button.setAttribute('aria-pressed',String(!visible));button.setAttribute('aria-label',visible?'Tampilkan password':'Sembunyikan password')}</script>
</body>
</html>
